
### 获取用户信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.youyou.yyrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [66677]
}

### 获取订单信息
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.youyou.yyrpc.demo.api.OrderService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [888]
}

### mock
POST http://localhost:8080/
Content-Type: application/json

{
  "service": "cn.youyou.yyrpc.demo.api.UserService",
  "methodSign": "hashCode",
  "args": []
}