### 获取8088用户信息
GET http://localhost:8088/api/?id=101

### 通过8088调用超时接口
GET http://localhost:8088/find/?timeout=1000

### 修改灰度比例值
GET http://localhost:8088/gray/?ratio=100

### 通过8081调用接口 修改超时
GET http://localhost:8082/ports?ports=8080,8094

### 获取用户信息
POST http://localhost:8081/yyrpc
Content-Type: application/json

{
  "service": "cn.youyou.yyrpc.demo.api.UserService",
  "methodSign": "findById@1_int",
  "args": [66677]
}

### 获取订单信息
POST http://localhost:8081/yyrpc
Content-Type: application/json

{
  "service": "cn.youyou.yyrpc.demo.api.OrderService",
  "methodSign": "findById@1_java.lang.Integer",
  "args": [888]
}

### mock
POST http://localhost:8081/yyrpc
Content-Type: application/json

{
  "service": "cn.youyou.yyrpc.demo.api.UserService",
  "methodSign": "hashCode",
  "args": []
}